In [1]:
%pip install nltk

Requirement already satisfied: nltk in /Users/wujiangqi/anaconda3/envs/dsc/lib/python3.8/site-packages (3.8.1)
Requirement already satisfied: click in /Users/wujiangqi/anaconda3/envs/dsc/lib/python3.8/site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in /Users/wujiangqi/anaconda3/envs/dsc/lib/python3.8/site-packages (from nltk) (1.3.2)
Requirement already satisfied: regex>=2021.8.3 in /Users/wujiangqi/anaconda3/envs/dsc/lib/python3.8/site-packages (from nltk) (2024.5.15)
Requirement already satisfied: tqdm in /Users/wujiangqi/anaconda3/envs/dsc/lib/python3.8/site-packages (from nltk) (4.62.3)
Note: you may need to restart the kernel to use updated packages.

In [2]:
# import statement
import pandas as pd
import numpy as np
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.sentiment import SentimentIntensityAnalyzer
nltk.download('vader_lexicon')
nltk.download('punkt')
nltk.download('stopwords')

import warnings
warnings.filterwarnings('ignore')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/wujiangqi/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!
[nltk_data] Downloading package punkt to /Users/wujiangqi/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/wujiangqi/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

## A statement of the problem you are investigating

## Why is this problem relevant? Or, what inspired you to investigate this problem?

## Read data

In [3]:
vlog = pd.read_csv('vlog.csv')

In [4]:
vlog.head(5)

,username,author_id,video_desc,video_id,upload_time,duration,was_duet,hashtags,music_artist,music_title,is_verified,author_followers,author_likes,author_hearts,author_video_count,saves,likes,shares,plays,comments
0,MagicalAquatic,7140140605107127342,Another use for 360 cam #ocean #sea #vlog #tra...,7143031687490882858,1663116673,20,{'duetFromId': '0'},"['ocean', 'sea', 'vlog', 'travel', 'scuba', 's...",Hollow Coves,Coastline,False,276100,434,4800000,607,32900,706200,3355,10300000,1949
1,jah‚ú∞,6961499315445482501,imma still try to keep em daily‚Ä¶ #LikeAMonarch...,7144924903270108462,1663557479,37,{'duetFromId': '0'},"['likeamonarch', 'sephoraconcealers', 'dayinmy...",jah‚ú∞,original sound,False,385500,30400,11900000,226,113900,2200000,9272,10200000,8096
2,Caroline Collins,6776019851430560774,From 2:45 AM to 4:59 AM ‚òïÔ∏è This is my Monday t...,7138820984827612459,1662136289,78,{'duetFromId': '0'},"['news', 'vlog']",Caroline Collins,original sound,False,1600000,27900,54600000,871,13700,663200,758,7700000,2215
3,ü¶ûCraw Kingdomüëë,6835639642319193094,üò© IM HAPPY NOW!!!! #chicharron #Mexican #somex...,7139230020718906666,1662231523,57,{'duetFromId': '0'},"['chicharron', 'mexican', 'somexican', 'food',...",ü¶ûCraw Kingdomüëë,RIP PEPPA PIG,False,3400000,13100,80700000,1813,13700,319500,3335,3800000,2720
4,Cassie Aran,6747490126719206405,HURRICANE IS GETTING WORSEüò≥ #daywithme #vlog #...,7147887060324584747,1664247151,63,{'duetFromId': '0'},"['daywithme', 'vlog', 'dailyvlog', 'dayintheli...",Petit Biscuit,Night Trouble,False,806900,2448,25200000,2801,27900,974200,2955,13500000,14800

## Basic info

In [5]:
vlog.shape

(999, 20)

In [6]:
vlog.dtypes

username              object
author_id              int64
video_desc            object
video_id               int64
upload_time            int64
duration               int64
was_duet              object
hashtags              object
music_artist          object
music_title           object
is_verified             bool
author_followers       int64
author_likes           int64
author_hearts          int64
author_video_count     int64
saves                  int64
likes                  int64
shares                 int64
plays                  int64
comments               int64
dtype: object

In [7]:
vlog.describe()

,author_id,video_id,upload_time,duration,author_followers,author_likes,author_hearts,author_video_count,saves,likes,shares,plays,comments
count,9.990000e+02,9.990000e+02,9.990000e+02,999.000000,9.990000e+02,999.000000,9.990000e+02,999.000000,999.000000,9.990000e+02,999.000000,9.990000e+02,999.000000
mean,5.587109e+18,7.111583e+18,1.660123e+09,71.123123,2.603743e+06,27191.977978,1.298660e+08,896.934935,66392.746747,1.369237e+06,25418.334334,1.128784e+07,6958.658659
std,2.671875e+18,4.059729e+17,3.459084e+07,60.975716,4.934415e+06,44366.418207,2.813079e+08,940.621728,68833.930573,7.942861e+05,58489.360109,9.370577e+06,9582.143570
min,1.431400e+04,1.091123e+17,1.466357e+09,0.000000,0.000000e+00,0.000000,0.000000e+00,1.000000,39.000000,2.733000e+05,21.000000,9.538000e+05,0.000000
25%,6.585407e+18,7.046933e+18,1.640742e+09,30.000000,2.175500e+05,2882.000000,8.500000e+06,249.500000,26700.000000,8.895000e+05,2783.000000,5.700000e+06,2128.000000
50%,6.781315e+18,7.153473e+18,1.665548e+09,57.000000,9.205000e+05,12000.000000,3.100000e+07,549.000000,47100.000000,1.100000e+06,7533.000000,8.600000e+06,3986.000000
75%,6.969483e+18,7.240934e+18,1.685911e+09,90.000000,3.050000e+06,30650.000000,1.123000e+08,1301.000000,82000.000000,1.600000e+06,20750.000000,1.320000e+07,8035.500000
max,7.318645e+18,7.357814e+18,1.713125e+09,441.000000,5.440000e+07,618600.000000,1.900000e+09,7169.000000,584400.000000,8.700000e+06,834600.000000,8.540000e+07,97800.000000

## Where did you get the data from?

## Description of the data

## Data Cleaning

In [8]:
vlog = vlog.fillna('')

In [9]:
# Cleaning all the special characters and emojis
emoji_pattern = re.compile("["
         u"\U0001F600-\U0001F64F"  # emoticons
         u"\U0001F300-\U0001F5FF"  # symbols & pictographs
         u"\U0001F680-\U0001F6FF"  # transport & map symbols
         u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
         u"\U0001F900-\U0001F9FF"  # supplementary symbols and pictographs
         u"\U0001FA70-\U0001FAFF"  # symbols and pictographs extended-A
         u"\U00002702-\U000027B0"  # Dingbats
         u"\U000024C2-\U0001F251" 
         "]+", flags=re.UNICODE) # The UNICODE pattern is generated by ChatGPT to detect emojis

for column in vlog.select_dtypes(include=['object']):
    vlog[column] = vlog[column].apply(lambda x: emoji_pattern.sub(r'', str(x)) if x else x)
# tokenize the video_desc with stop words
stop_words = set(stopwords.words('english'))

In [10]:
def tokenize_without_stopwords_and_symbols(text):
    tokens = word_tokenize(text.lower())
    filtered_tokens = [word for word in tokens if word not in stop_words and re.match('^[a-zA-Z0-9]+$', word)]
    return filtered_tokens
def convert_to_list(hashtag_str):
    hashtags = hashtag_str.strip("[]").split("', '")
    hashtags = [tag.strip("'") for tag in hashtags if tag != '' and tag != "''" and tag != ","]
    return hashtags

vlog['hashtags'] = vlog['hashtags'].apply(convert_to_list)
vlog['video_desc'] = vlog['video_desc'].apply(tokenize_without_stopwords_and_symbols)

# transforming the upload_time to pd.datetime
vlog['upload_time'] = pd.to_datetime(vlog['upload_time'], unit= 's')

In [11]:
vlog = vlog.drop(columns = ['was_duet', 'music_artist', 'is_verified', 'author_likes', 'author_hearts', 'music_title'])

In [12]:
sia = SentimentIntensityAnalyzer()
vlog['video_desc_str'] = vlog['video_desc'].apply(' '.join)

# Define a function to get sentiment score
def get_sentiment_score(text):
    return sia.polarity_scores(text)['compound']

# Apply the function to the string version of video_desc
vlog['sentiment_score'] = vlog['video_desc_str'].apply(get_sentiment_score)

In [13]:
vlog.head(5)

,username,author_id,video_desc,video_id,upload_time,duration,hashtags,author_followers,author_video_count,saves,likes,shares,plays,comments,video_desc_str,sentiment_score
0,MagicalAquatic,7140140605107127342,"[another, use, 360, cam, ocean, sea, vlog, tra...",7143031687490882858,2022-09-14 00:51:13,20,"[ocean, sea, vlog, travel, scuba, snorkling, s...",276100,607,32900,706200,3355,10300000,1949,another use 360 cam ocean sea vlog travel scub...,0.0000
1,jah,6961499315445482501,"[imma, still, try, keep, em, likeamonarch, sep...",7144924903270108462,2022-09-19 03:17:59,37,"[likeamonarch, sephoraconcealers, dayinmylife,...",385500,226,113900,2200000,9272,10200000,8096,imma still try keep em likeamonarch sephoracon...,0.0000
2,Caroline Collins,6776019851430560774,"[monday, friday, mornings, news, anchor, news,...",7138820984827612459,2022-09-02 16:31:29,78,"[news, vlog]",1600000,871,13700,663200,758,7700000,2215,monday friday mornings news anchor news vlog,0.0000
3,Craw Kingdom,6835639642319193094,"[im, happy, chicharron, mexican, somexican, fo...",7139230020718906666,2022-09-03 18:58:43,57,"[chicharron, mexican, somexican, food, pork, c...",3400000,1813,13700,319500,3335,3800000,2720,im happy chicharron mexican somexican food por...,0.8225
4,Cassie Aran,6747490126719206405,"[hurricane, getting, worse, daywithme, vlog, d...",7147887060324584747,2022-09-27 02:52:31,63,"[daywithme, vlog, dailyvlog, dayinthelife, day...",806900,2801,27900,974200,2955,13500000,14800,hurricane getting worse daywithme vlog dailyvl...,-0.8360

## EDA